server/hklirc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('remote.urls')),
    path('admin/', admin.site.urls),
]

server/remote/urls.py
from django.urls import path
from .views import views_lirc, views_mapping

urlpatterns = [
    path('', views_lirc.index, name="index"),
    #path('refresh', views_mapping.update_map, name="refresh_mapping"),
    path('lirc', views_lirc.lircd_remotes, name="lircd_remotes"),
    path('lirc/<remote_file>', views_lirc.lircd_remote, name="lircd_remote"),
    path('lirc/<remote_file>/download', views_lirc.lircd_remote_download, name="lircd_remote_download"),
    path('lirc/<remote_file>/delete', views_lirc.lircd_remote_delete, name="lircd_remote_delete"),
    path('mapping', views_mapping.index, name="mapping_index"),
    path('mapping/<mapping_id>', views_mapping.detail, name="mapping_detail"),
    path('mapping/<mapping_id>/activate', views_mapping.activate, name="mapping_activate"),
    path('mapping/<mapping_id>/delete', views_mapping.delete, name="mapping_delete"),
]

server/remote/models.py
from django.db import models

# Create your models here.
# python manage.py makemigrations <app_name>
# python manage.py migrate

class Mapping(models.Model):
    active = models.BooleanField(default=False)
    name = models.CharField(max_length=255)
    config = models.TextField()

server/remote/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()

server/remote/views/views_lirc.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.conf import settings as ConfigSettings
from os import listdir, remove
from os.path import isfile, join, basename, exists
import json, re
from ..util.LircdParser import parse as parseLirc
from ..forms import UploadFileForm

# Create your views here.
# form: https://www.youtube.com/watch?v=pH6X79wIgyY

def index(request):
    return render(request, "remote/empty.html", {})

def handle_uploaded_file(f, folder):
    with open(join(folder, f.name), 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

def lircd_remotes(request):
    mypath = ConfigSettings.LIRCD_PATH
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            print(file) # handle_uploaded_file
            handle_uploaded_file(file, mypath)
            # return HttpResponseRedirect('/success/url/')
    else:
        form = UploadFileForm()
    
    remotes = parseLirc(mypath)
    return render(request, "remote/lircd_remotes.html", {
        'remotes': remotes,
        'lircd_path': mypath,
        'file_form': form    
    })

def lircd_remote(request, remote_file):
    remote_file_path = ConfigSettings.LIRCD_PATH + basename(remote_file)
    print(remote_file_path)
    remotes = parseLirc(remote_file_path)
    file = open(remote_file_path,"r")
    config = file.read()
    file.close()
    return render(request, "remote/lircd_remote.html", {
        'remote': {"config":config, "filename":remote_file}, "remotes": remotes
    })

def lircd_remote_download(request, remote_file):
    remote_file_path = ConfigSettings.LIRCD_PATH + basename(remote_file)
    if exists(remote_file_path):
        with open(remote_file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + basename(remote_file_path)
            return response
    raise Http404

def lircd_remote_delete(request, remote_file):
    remote_file_path = ConfigSettings.LIRCD_PATH + basename(remote_file)
    if exists(remote_file_path):
        remove(remote_file_path)
        return redirect('lircd_remotes')
    raise Http404

server/remote/views/views_mapping.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.conf import settings as ConfigSettings
from os import listdir, kill
from os.path import isfile, join, basename, exists
import json, re
from ..models import Mapping
from ..util.LircdParser import parse as parseLirc
from django.template.defaulttags import register
import signal

@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

def loadMap(file):
    all_keys = []
    with (open(file, "r")) as f:
        all_keys = json.loads(f.read()).keys()
    return all_keys

def index(request):
    mappings = Mapping.objects.all()
    return render(request, "remote/mappings.html", {
        "mappings": mappings,
    })

def detail(request, mapping_id):
    if mapping_id == 'NEW':
        mapping = Mapping(config="{}")
    else:
        mapping = get_object_or_404(Mapping, pk=mapping_id)
    
    if (request.POST.get("submitted", None) is not None):
        new_mapping = {}
        print(request.POST.dict())
        for key, value in request.POST.dict().items():
            if key.startswith("mapping_") and value is not "":
                new_mapping[key.replace("mapping_","")] = value
            if key == 'general_name':
                mapping.name = value
        mapping.config = json.dumps(new_mapping)
        mapping.save()
        if (mapping.active):
            # We update the mapping in the daemon
            signal_daemon(ConfigSettings.DAEMON_FILE)
        return redirect('mapping_index')
    

    mypath = ConfigSettings.LIRCD_PATH
    remotes = parseLirc(mypath)
    available_keys = []
    for _, value in remotes.items():
        for key in value['codes']:
            if key not in available_keys:
                available_keys.append(key)

    
    return render(request, "remote/mapping_detail.html", {
        "mapping": mapping,
        "mapping_codes": json.loads(mapping.config),
        "remotes": remotes,
        "available_keys": available_keys,
        "all_keys": loadMap(str(ConfigSettings.BASE_DIR) + "/../standard_map.json")
    })

def activate(request, mapping_id):
    mappings = Mapping.objects.all()
    for m in mappings:
        # Just one can be active
        m.active = (str(m.id) == str(mapping_id))
        m.save()

    # We update the mapping in the daemon
    signal_daemon(ConfigSettings.DAEMON_FILE)

    return redirect('mapping_index')

def delete(request, mapping_id):
    mapping = get_object_or_404(Mapping, pk=mapping_id)
    mapping.delete()
    return redirect('mapping_index')

def update_map(request):
    # We update the mapping in the daemon
    signal_daemon(ConfigSettings.DAEMON_FILE)
    return redirect('index')


def signal_daemon(pid_file):
    if exists(pid_file):
        with open(pid_file,'r') as f:
            pid = int(f.read())
            kill(pid, signal.SIGUSR1)

server/remote/templates/adminltetop/body.html
{% extends 'adminltetop/home.html' %}
{% block body %}

<body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'adminltetop/header.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> {% block page_name %}page_name{% endblock %}
                                <small class="text-muted" style="font-style: italic;">{% block page_description %}page_description{% endblock %}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                {% block breadcrumb-items %}
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Layout</a></li>
                                {% endblock %}
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'adminltetop/footer.html' %}

        {% block footer_left %}{% endblock %}
        

        
    </div>
</body>
{% endblock %}

server/remote/templates/adminltetop/footer.html
<style>
    .no-footer {
    background: #f4f6f9;
    border-top: 0 !important; 
    padding: 1rem;
}
</style>

<footer class="main-footer no-footer">
    <div class="float-right d-none d-sm-block">
    {% block footer_right %}{% endblock %}
</div>

{% block footer_left %}
{% block legal %}
{% endblock %}
{% endblock %}
</footer>

server/remote/templates/adminltetop/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
        <a href="/" class="navbar-brand">
            <span class="brand-text font-weight-light"><i class="fas fa-gamepad"></i> hklirc</span>
        </a>

        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                  <li class="nav-item">
                    <a href="{% url 'lircd_remotes' %}" class="nav-link">Remotes</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'mapping_index' %}" class="nav-link">Mappings</a>
                </li>
                {% comment %}
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                        class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Mantenimientos</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="#" class="dropdown-item"><i class="fas fa-truck-loading"></i> Categorías</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-boxes"></i> Productos</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-users"></i> Clientes</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-shopping-cart"></i> Ventas</a></li>
                    </ul>
                </li>
                {% endcomment %}
            </ul>
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="fas fa-sliders-h"></i>
                    <!--<span class="badge badge-warning navbar-badge">15</span>-->
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    {% comment %}
                    <span class="dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'refresh_mapping' %}" class="dropdown-item">
                        <i class="fas fa-sync mr-2"></i>Refresh
                    </a>
                    <div class="dropdown-divider"></div>
                    {% endcomment %}
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-power-off mr-2"></i>Reboot
                    </a>
                    {% comment %}
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    {% endcomment %}
                    {% comment %}
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    {% endcomment %}
                </div>
            </li>
        </ul>
    </div>
</nav>

server/remote/templates/adminltetop/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'dist/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'dist/favicon.ico' %}" type="image/x-icon">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
</head>
{% block body %}

{% endblock %}
</html>

server/remote/templates/remote/_confirmation-logic.html
<div class="modal fade" id="confirmation-modal" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Confirmation</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to continue?</p>
        </div>
        <div class="modal-footer justify-content-between">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <a href="#" type="button" class="btn bg-navy" id="proceed">Continue</a>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>

  <script>
      $('a.confirmWithModal').click(function(e){
        e.preventDefault();
        $('a#proceed').attr('href',$(this).attr('href'))
        $('#confirmation-modal').modal('show');
      })
  </script>

server/remote/templates/remote/empty.html
{% extends 'adminltetop/body.html' %}

{% block title %}hklirc{% endblock %}
{% block page_name %}{% endblock %}
{% block page_description %}{% endblock %}

{% block content %}
{% endblock %}

{% block breadcrumb-items %}
{% endblock %}

server/remote/templates/remote/lircd_remote.html
{% extends 'adminltetop/body.html' %}

{% block title %}hklirc: lircd/{{ remote.filename }}{% endblock %}
{% block page_name %}File{% endblock %}
{% block page_description %}{{ remote.filename }}{% endblock %}

{% block breadcrumb-items %}
<li class="breadcrumb-item"><a href="{% url 'lircd_remotes' %}" class="text-navy">Infrared</a></li>
<li class="breadcrumb-item" class="active">{{remote.filename}}</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12 col-md-4">
        <div class="card">
            <div class="card-header">
                <span class="card-title"><span class="text-muted">Remotes on file:</span></span>
            </div>
            <ul class="list-group list-group-flush">
                {% for name, r in remotes.items %}
                <li class="list-group-item">{{ name }}

                    <span class="float-right badge bg-navy">{{r.codes | length}}</span>
                </li>
                {% endfor %}
            </ul>
            <div class="card-body text-right">
                <a href="{% url 'lircd_remote_delete' remote.filename %}"  class="card-link text-danger confirmWithModal">Remove</a>
                <a href="{% url 'lircd_remote_download' remote.filename %}" class="card-link text-navy">Download</a>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-md-8">
        <div class="card card-body">
            <pre>{{remote.config}}</pre>
        </div>
    </div>

</div>
{# Use class .confirmWithModal to activate the modal #}
{% include 'remote/_confirmation-logic.html' %}

{% endblock %}

server/remote/templates/remote/lircd_remotes.html
{% extends 'adminltetop/body.html' %}

{% block title %}hklirc{% endblock %}
{% block page_name %}Remotes{% endblock %}
{% block page_description %}{{lircd_path}}{% endblock %}

{% block breadcrumb-items %}
<li class="breadcrumb-item">Infrared</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12 col-md-8">
        <div class=" card card-body p-0">
            <table class="table table-striped">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>File</th>
                    <th class="text-right">Buttons</th>
                </tr>
                {% for name, r in remotes.items %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>
                        <a href="{% url 'lircd_remote' r.filename %}" class="text-navy">{{name}}</a>
                    </td>
                    <td>{{r.filename}}</td>
                    <td class="text-right">{{r.codes|length}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="col-xs-12 col-md-4">
        <div class="card">
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data"> 
                    {% csrf_token %} 
                    <p class="card-text">Upload a new remote to the server. <br />
                        <span class="text-muted"><i>It has to be lirc <a
                                    href="https://sourceforge.net/p/lirc-remotes/code/ci/master/tree/remotes/"
                                    target="_blank" class="text-navy">compatible</a></i></span>
                    </p>
                    <div class="form-group">
                        <div class="custom-file">
                            <input type="file" name="file" class="custom-file-input" id="id_file">
                            <label class="custom-file-label" for="id_file">Choose file</label>
                        </div>
                    </div>
                    <div class="text-right"><input type="submit" class="btn text-navy" name="upload" value="Upload"/></div>
                </form>
            </div>
        </div>

    </div>
</div>

<script>
    $('#id_file').on('change',function(){
        //get the file name
        var fileName = $(this).val().split("\\").pop();
        //replace the "Choose a file" label
        $(this).next('.custom-file-label').html(fileName);
    })
</script>
{% endblock %}

server/remote/templates/remote/mapping_detail.html
{% extends 'adminltetop/body.html' %}

{% block title %}Mappings{% endblock %}
{% block page_name %}{{ mapping.name }}{% endblock %}
{% block page_description %}Edit{% endblock %}

{% block breadcrumb-items %}
<li class="breadcrumb-item"><a href="{% url 'mapping_index' %}" class="text-navy">Mappings</a></li>
<li class="breadcrumb-item">{{mapping.name}}</li>
{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Name" name="general_name"
                            value="{{mapping.name}}">
                        {% if mapping.active %}
                        <div class="input-group-append">
                            <span class="input-group-text text-navy">Active</span>
                        </div>
                        {% endif %}
                    </div>


                </div>
                <ul class="list-group list-group-flush" id="key_map_list">
                    <li class="list-group-item key" style="display: none" id="key_map_template"
                        key="KEY_CODE_TO_REPLACE">
                        <div class="row">
                            <div class="col-sm-4">
                                KEY_CODE_TO_REPLACE
                            </div>
                            <div class="col-sm-2 text-center">
                                <i class="fas fa-arrow-right align-bottom"></i>
                            </div>
                            <div class="col-sm-5">
                                <div class="form-group input-group">
                                    <select name="mapping_KEY_CODE_TO_REPLACE" class="form-control custom-select">
                                        {% for key_code in all_keys %}
                                        <option value="{{key_code}}">{{key_code}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-1 text-right">
                                <a href="javascript:removeKeyMap('KEY_CODE_TO_REPLACE')" class="btn text-danger"><i
                                        class="fas fa-times"></i></a>
                            </div>
                        </div>
                    </li>
                    {% for key in mapping_codes %}
                    <li class="list-group-item key" key="{{key}}" id="{{key}}">
                        <div class="row">
                            <div class="col-sm-4">
                                {{key}}
                            </div>
                            <div class="col-sm-2 text-center">
                                <i class="fas fa-arrow-right align-bottom"></i>
                            </div>
                            <div class="col-sm-5">
                                <div class="form-group input-group">
                                    <select name="mapping_{{key}}" class="form-control custom-select">
                                        {% for key_code in all_keys %}
                                        {% if mapping_codes|get_item:key == key_code %}
                                        <option selected value="{{key_code}}">{{key_code}}</option>
                                        {% else %}
                                        <option value="{{key_code}}">{{key_code}}</option>
                                        {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-1 text-right">
                                <a href="javascript:removeKeyMap('{{key}}')" class="btn text-danger"><i
                                        class="fas fa-times"></i></a>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
                <div class="card-footer text-center">
                    <a href="#" class="btn text-navy" id="addMapping"><i class="fas fa-plus"></i> Map a new Key</a>
                </div>
            </div>
</form>
</div>
<div class="col-xs-12 col-md-4">
    <input type="submit" class="btn btn-block bg-navy" name="submitted" value="Save" /><br />

    <div class="card">
        <div class="card-header">
            <span class="card-title"><span class="text-muted">Remotes & Keys</span></span>
        </div>
        <ul class="list-group list-group-flush">
            {% for key, value in remotes.items %}
            <li class="list-group-item">{{ key }} <br />

                {% for key_code in value.codes %}
                <span class="badge bg-navy">{{key_code}}</span>
                {% endfor %}
            </li>
            {% endfor %}
        </ul>
    </div>
    <a class="btn btn-block btn-danger" href="{% url 'mapping_delete' mapping.id %}">Delete</a>
</div>

</div>
</form>
<script>
    $('option:selected').each(function () { $(this).prop('selected', true); });
</script>

<div class="modal fade" id="mapping-modal" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Which button do you want to map?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <ul class="list-group list-group-flush">
                {% for key, value in remotes.items %}
                <li class="list-group-item">{{ key }} <br />

                    {% for key_code in value.codes %}
                    <a href="#{{key_code}}" class="remote_button button_{{key_code}}" {% if key_code in mapping_codes %}
                        style="display:none;" {% endif %}><span class="badge bg-navy">{{key_code}}</span></a>
                    {% endfor %}
                </li>
                {% endfor %}
            </ul>
            <div class="modal-footer text-center text-muted">
                <small>Click on a button to continue.</small>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<script>

    $('a#addMapping').click(function (e) {
        e.preventDefault();
        $('#mapping-modal').modal('show');
    })

    $('a.remote_button').click(function (e) {
        e.preventDefault();
        var pressedKey = $(this).attr('href').replace("#", "");

        var proceed = true;
        $("li.key").each(function (e) {
            if ($(this).attr("key") == pressedKey)
                proceed = false;
        })

        if (proceed) {
            var template = $('<div>').append($('li#key_map_template').clone().show()).html();
            template = template.replaceAll("KEY_CODE_TO_REPLACE", pressedKey)
            template = template.replaceAll('key_map_template', pressedKey)
            $('ul#key_map_list').append($.parseHTML(template));
            $('a.button_' + pressedKey).hide()
        }

        $('#mapping-modal').modal('hide');
    })

    function removeKeyMap(key) {
        $('li#' + key).remove()
        $('a.button_' + key).show()
    }
</script>

{% endblock %}

server/remote/templates/remote/mapping_detail_back.html
{% extends 'adminltetop/body.html' %}

{% block title %}Mappings{% endblock %}
{% block page_name %}{{ mapping.name }}{% endblock %}
{% block page_description %}Edit{% endblock %}

{% block breadcrumb-items %}
<li class="breadcrumb-item"><a href="{% url 'mapping_index' %}" class="text-navy">Mappings</a></li>
<li class="breadcrumb-item">{{mapping.name}}</li>
{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Name" name="general_name"
                        value="{{mapping.name}}">
                        {% if mapping.active %}
                        <div class="input-group-append">
                          <span class="input-group-text text-navy">Active</span>
                        </div>
                        {% endif %}
                      </div>
                    

                </div>
                <ul class="list-group list-group-flush">
                    {% for key in available_keys %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-sm-5">
                                {{key}}
                            </div>
                            <div class="col-sm-2 text-center">
                                <i class="fas fa-arrow-right align-bottom"></i>
                            </div>
                            <div class="col-sm-5">
                                <div class="form-group input-group">
                                    <select name="mapping_{{key}}" class="form-control custom-select">
                                        <!-- If it is not yet mapped, we select the empty one -->
                                        <option {% if key not in mappings_codes %} selected {% endif %}></option>
                                        {% for key_code in all_keys %}
                                        {% if mapping_codes|get_item:key == key_code %}
                                        <option selected value="{{key_code}}">{{key_code}}</option>
                                        {% else %}
                                        <option value="{{key_code}}">{{key_code}}</option>
                                        {% endif %}
                                        {% endfor %}
                                    </select>
                                    <!--
                                <span class="input-group-append">
                                    <button type="button" class="btn btn-navy btn-flat"><i
                                            class="fas fa-plus"></i></button>
                                </span>
                            -->
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
</form>
</div>
<div class="col-xs-12 col-md-4">
    <input type="submit" class="btn btn-block bg-navy" name="submitted" value="Save" /><br/>

    <div class="card">
        <div class="card-header">
            <span class="card-title"><span class="text-muted">Remotes & Keys</span></span>
        </div>
        <ul class="list-group list-group-flush">
            {% for key, value in remotes.items %}
            <li class="list-group-item">{{ key }} <br />

                {% for key_code in value.codes %}
                <span class="badge bg-navy">{{key_code}}</span>
                {% endfor %}
            </li>
            {% endfor %}
        </ul>
    </div>
    <a class="btn btn-block btn-danger" href="{% url 'mapping_delete' mapping.id %}">Delete</a>
</div>
{% comment %}
<div class="col-xs-12 col-md-8">
    <textarea name="remote_config" class="form-control" id="remote_config" cols="255"
        rows="10">{{mapping.config}}</textarea>
</div>
{% endcomment %}
</div>
</form>
<script>
    $('option:selected').each(function () { $(this).prop('selected', true); });
</script>

{% endblock %}